package dev.minifilm.director;

import android.Manifest;
import android.app.AlertDialog;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaMetadataRetriever;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.activity.ComponentActivity;
import androidx.camera.view.PreviewView;
import androidx.camera.core.CameraSelector;
import androidx.core.content.FileProvider;
import org.json.*;
import java.io.*;
import java.util.*;

/** Pre-event research, 4 October 2026. All camera/microphone activity is explicit. */
public class MainActivity extends ComponentActivity {
    private final int BG=0xff101113, CARD=0xff1d1f22, FG=0xfff5f5ef, MUTED=0xffa8aaa4, LIME=0xffd9ff70;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private LinearLayout root,content,nav; private String reelTitle=""; private TextView status,cueView,timerView; private Button cancelProcessingButton; private EditText briefField;
    private volatile int saveGeneration=0; private int demoGeneration=0; private int desiredLens=CameraSelector.LENS_FACING_FRONT; private TextView selectionSummary; private Button captureAction; private TextView cameraPlaceholder; private boolean guideSequence=false, sequenceActive=false; private PreviewView preview; private CaptureController capture; private PoseCoach pose; private SpeechCoach speech; private ReelExporter exporter;
    private AutoColorBalance autoColor; private ProjectPackager packager; private File pendingPack; private boolean savingDocument; private LocalPlanner planner; private ClipTranscriber transcriber; private ReferenceAnalyzer references; private String referenceSummary=""; private boolean busy=false, session=false, voice=true, autoStop=true, countdown=false, live=false;
    private long recordStart=0,lastCue=0; private int tab=0,shotIndex=0; private String brief="20-second streetwear reel. Show my jacket, a confident walk and the details.", style="Fashion", look="Clean", planSource="Editable starter plan";
    private final ArrayList<Shot> shots=new ArrayList<>(); private final ArrayList<Take> takes=new ArrayList<>(); private Uri lastVideo,lastEdit;
    private Shot recordingShot; private int countdownGeneration=0; private boolean reviewAfterSave=false; private TextView framingView;
    @Override public void onCreate(Bundle state){super.onCreate(state);speech=new SpeechCoach(this);exporter=new ReelExporter(this);packager=new ProjectPackager(this);autoColor=new AutoColorBalance(this);planner=new LocalPlanner(this);transcriber=new ClipTranscriber(this);references=new ReferenceAnalyzer(this);restore();recoverTakes();ExportRecovery.Result recovered=ExportRecovery.reconcile(this);if(recovered.videoUri!=null){lastVideo=recovered.videoUri;lastEdit=recovered.editListUri;save();}if(shots.isEmpty())shots.addAll(DirectorEngine.plan(brief,style));render();if(!recovered.warning.isEmpty())status.setText(recovered.warning);else if(recovered.cleaned>0)status.setText("Interrupted export cleared. Original clips are safe.");}
    private int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));return t;}
    private GradientDrawable bg(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(18));return d;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
    private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(18),dp(14),dp(18),dp(14));l.setBackground(bg(CARD));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);l.setLayoutParams(p);return l;}
    private Button button(String s,boolean primary,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(primary?BG:FG);b.setBackground(bg(primary?LIME:0xff303338));b.setMinHeight(dp(50));b.setPadding(dp(12),dp(8),dp(12),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.topMargin=dp(8);p.bottomMargin=dp(4);b.setLayoutParams(p);b.setOnClickListener(v->{if(busy){toast("Local processing is running. You can cancel it above.");return;}action.run();});return b;}
    private EditText input(String value,String hint){EditText e=new EditText(this);e.setText(value);e.setHint(hint);e.setTextColor(FG);e.setHintTextColor(MUTED);e.setTextSize(16);e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setBackground(bg(0xff292c30));return e;}
    private void render(){
        if(capture!=null){desiredLens=capture.getLensFacing();capture.stopPreview();capture.close();capture=null;}if(pose!=null){pose.close();pose=null;}live=false;
        root=column();root.setBackgroundColor(BG);root.setPadding(dp(22),dp(22),dp(22),dp(10));androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{androidx.core.graphics.Insets bars=insets.getInsets(androidx.core.view.WindowInsetsCompat.Type.systemBars());v.setPadding(dp(22)+bars.left,dp(16)+bars.top,dp(22)+bars.right,dp(10)+bars.bottom);return insets;});
        TextView brand=text("mini film  /  your pocket director",15,LIME);brand.setTypeface(null,Typeface.BOLD);root.addView(brand);
        status=text(busy?"Working locally…":"Research preview · made locally on your phone",11,MUTED);root.addView(status);cancelProcessingButton=button("Cancel local processing",false,()->{});cancelProcessingButton.setOnClickListener(v->cancelProcessing());cancelProcessingButton.setVisibility(busy?View.VISIBLE:View.GONE);root.addView(cancelProcessingButton);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=column();content.setPadding(0,dp(12),0,dp(18));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this);String[] labels={"01  Brief","02  Direct","03  Assemble"};for(int i=0;i<3;i++){final int n=i;Button b=button(labels[i],tab==i,()->switchTab(n));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);p.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(p);b.setTextSize(12);nav.addView(b);}root.addView(nav);setContentView(root);
        if(tab==0)briefPage();else if(tab==1){directPage();LinearLayout controls=new LinearLayout(this);Button record=button("Start camera",true,()->{if(live)startCountdown();else startShoot();}),stop=button("Stop take",false,()->stopTake());captureAction=record;stop.setTextColor(0xffff9e9e);for(Button b:new Button[]{record,stop}){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(50),1);lp.setMargins(dp(3),dp(4),dp(3),dp(8));b.setLayoutParams(lp);controls.addView(b);}root.addView(controls,root.getChildCount()-1);}else editPage();
    }
    private void setBusy(boolean value){busy=value;if(cancelProcessingButton!=null)cancelProcessingButton.setVisibility(value?View.VISIBLE:View.GONE);setEditorsEnabled(root,!value);}
    private void setEditorsEnabled(View view,boolean enabled){if(view==null)return;if(view instanceof EditText||view instanceof Spinner||view instanceof CheckBox||view instanceof Switch)view.setEnabled(enabled);if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)setEditorsEnabled(group.getChildAt(i),enabled);}}
    private void cancelProcessing(){boolean interruptedDocument=savingDocument;savingDocument=false;++saveGeneration;++demoGeneration;exporter.cancel();packager.cancel();autoColor.close();autoColor=new AutoColorBalance(this);planner.close();transcriber.close();references.close();planner=new LocalPlanner(this);transcriber=new ClipTranscriber(this);references=new ReferenceAnalyzer(this);setBusy(false);save();render();status.setText(interruptedDocument?"Save stopped. The chosen document may be partial; save again with a new name. Original clips are safe.":"Processing stopped. Your clips and edits are safe.");}
    private void switchTab(int n){if(busy){toast("Wait for the current operation to finish.");return;}if(countdown || capture!=null&&capture.isRecording()){toast("Stop this take before changing screens.");return;}sequenceActive=false;cancelCountdown();speech.stopListening();speech.stop();session=false;tab=n;save();render();}
    private void headline(String title,String sub){TextView h=text(title,32,FG);h.setTypeface(null,Typeface.BOLD);content.addView(h);content.addView(text(sub,15,MUTED));}
    private void briefPage(){
        headline("Make something\nworth watching.","One idea. A few good takes. Your reel, made here.");
        LinearLayout c=card();c.addView(text("WHAT ARE WE MAKING?",11,LIME));briefField=input(brief,"Describe your reel, outfit, story or reference trend");briefField.setMinLines(3);briefField.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){brief=s.toString();}public void afterTextChanged(android.text.Editable e){}});c.addView(briefField);c.addView(text("Describe a trend's beats or import your own reference clips. Automatic trend analysis is still research.",12,MUTED));
        Spinner modes=spinner(new String[]{"Fashion","Talking head","Product reveal","Introduction"},style,s->{style=s;save();});c.addView(modes);
        c.addView(button("Speak my brief",false,()->listenBrief()));
        c.addView(button("Build my shot plan",true,()->generatePlan()));c.addView(button("Inspect a reference reel locally",false,()->pickReference()));if(!referenceSummary.isEmpty()){c.addView(text("Sampled reference observations: "+referenceSummary,12,MUTED));c.addView(button("Clear reference observations",false,()->{referenceSummary="";save();render();}));}content.addView(c);
        content.addView(text(planSource+" · "+shots.size()+" shots",12,LIME));
        for(int i=0;i<shots.size();i++){final int index=i;Shot shot=shots.get(i);LinearLayout s=card();s.addView(text(String.format(Locale.US,"%02d  /  %s",i+1,shot.title),20,FG));s.addView(text(shot.instruction,14,MUTED));s.addView(text((shot.targetDurationMs/1000)+" sec · Phone camera",12,LIME));s.addView(button("Edit shot",false,()->editShot(index)));if(i>0)s.addView(button("Move earlier",false,()->{Collections.swap(shots,index,index-1);save();render();}));content.addView(s);}
        content.addView(button("Let's direct this reel →",true,()->{brief=briefField.getText().toString();switchTab(1);}));
        content.addView(button("Try a synthetic demo",false,()->loadDemo()));
    }
    private Spinner spinner(String[] values,String selected,java.util.function.Consumer<String> action){Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values){@Override public View getView(int p,View c,android.view.ViewGroup g){TextView v=(TextView)super.getView(p,c,g);v.setTextColor(FG);v.setPadding(dp(12),dp(12),dp(12),dp(12));return v;}};s.setAdapter(a);s.setSelection(Math.max(0,Arrays.asList(values).indexOf(selected)));s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int n,long id){action.accept(values[n]);}});return s;}
    private void generatePlan(){brief=briefField.getText().toString().trim();if(brief.isEmpty()){toast("Add a brief first.");return;}if(takes.size()>0){new AlertDialog.Builder(this).setTitle("Replace shot plan?").setMessage("Your existing takes stay in Assemble. The new plan starts from shot one.").setPositiveButton("Replace plan",(d,w)->runPlanner()).setNegativeButton("Keep plan",null).show();}else runPlanner();}
    private void runPlanner(){speech.stopListening();speech.stop();save();if(!planner.isModelAvailable()){shots.clear();shots.addAll(DirectorEngine.plan(brief,style));planSource="Editable template · local LLM not installed";shotIndex=0;save();render();return;}setBusy(true);status.setText("Local model is creating your shot plan…");planner.generate(brief+(referenceSummary.isEmpty()?"":"\nReference sampled observations (approximate, no style inferred): "+referenceSummary),style,new LocalPlanner.Listener(){public void onPlan(List<Shot> p,long ms,String model){setBusy(false);shots.clear();shots.addAll(p);shotIndex=0;planSource="Local AI · "+model+" · "+String.format(Locale.US,"%.1fs",ms/1000.0);save();render();}public void onError(String error){setBusy(false);toast(error);status.setText("Local model unavailable. Keep your plan or use the starter.");new AlertDialog.Builder(MainActivity.this).setTitle("Keep creating").setMessage(error).setPositiveButton("Use starter plan",(d,w)->{shots.clear();shots.addAll(DirectorEngine.plan(brief,style));planSource="Editable template · AI failed";save();render();}).setNegativeButton("Keep current",null).show();}});}
    private void listenBrief(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},42);return;}status.setText("Listening locally… tap another screen to stop");speech.listen(new SpeechCoach.Listener(){public void onText(String t){brief=t;if(briefField!=null)briefField.setText(t);status.setText("Voice brief ready for your review");save();}public void onError(String e){status.setText(e);toast(e);}});}
    private void editShot(int i){Shot s=shots.get(i);LinearLayout form=column();form.setPadding(dp(20),dp(10),dp(20),dp(10));EditText name=input(s.title,"Title"),cue=input(s.instruction,"Direction"),caption=input(s.caption,"Manual caption"),duration=input(""+(s.targetDurationMs/1000),"Seconds");duration.setInputType(2);form.addView(name);form.addView(cue);form.addView(caption);form.addView(duration);new AlertDialog.Builder(this).setTitle("Your shot").setView(form).setPositiveButton("Save",(d,w)->{long seconds=6;try{seconds=Long.parseLong(duration.getText().toString());}catch(Exception ignored){}shots.set(i,new Shot(s.id,name.getText().toString(),cue.getText().toString(),caption.getText().toString(),Math.max(2,Math.min(60,seconds))*1000));save();render();}).setNegativeButton("Cancel",null).show();}
    private void directPage(){
        shotIndex=Math.min(shotIndex,Math.max(0,shots.size()-1));Shot shot=shots.get(shotIndex);
        headline("Your next good shot.",String.format(Locale.US,"SHOT %02d OF %02d  ·  %s",shotIndex+1,shots.size(),shot.title));
        FrameLayout frame=new FrameLayout(this);frame.setBackground(bg(CARD));preview=new PreviewView(this);preview.setImplementationMode(PreviewView.ImplementationMode.COMPATIBLE);preview.setScaleType(PreviewView.ScaleType.FILL_CENTER);int viewfinderHeight=Math.min(dp(390),(int)(getResources().getDisplayMetrics().heightPixels*.42f));FrameLayout.LayoutParams viewfinderBounds=new FrameLayout.LayoutParams((int)(viewfinderHeight*9f/16f),viewfinderHeight,Gravity.CENTER);frame.addView(preview,viewfinderBounds);
        TextView placeholder=text("Mount your phone vertically.\nLeave it steady for the shoot.\nTap Start camera to begin.",16,MUTED);cameraPlaceholder=placeholder;placeholder.setGravity(Gravity.CENTER);frame.addView(placeholder,new FrameLayout.LayoutParams(-1,-1));
        content.addView(frame,new LinearLayout.LayoutParams(-1,viewfinderHeight));
        LinearLayout c=card();c.setPadding(dp(18),dp(16),dp(18),dp(16));cueView=text(shot.instruction,21,FG);c.addView(cueView);framingView=text(isPoseShot()?"Framing coach waits for your shoot to start":"Person-framing advice is off for this object shot. Follow your scene cue.",13,MUTED);c.addView(framingView);timerView=text("Ready when you are · "+shot.targetDurationMs/1000+" second take",13,LIME);c.addView(timerView);
        Switch v=new Switch(this);v.setText("Spoken direction / earbuds");v.setTextColor(FG);v.setChecked(voice);v.setOnCheckedChangeListener((b,on)->{voice=on;if(!on){if(countdown)stopTake();else speech.stop();}save();});c.addView(v);
        Switch sequence=new Switch(this);sequence.setText("Guide the full shot sequence");sequence.setTextColor(FG);sequence.setChecked(guideSequence);sequence.setOnCheckedChangeListener((b,on)->{guideSequence=on;if(!on){sequenceActive=false;cancelCountdown();speech.stop();if(pose!=null)pose.setEnabled(session&&isPoseShot());}save();});c.addView(sequence);c.addView(text("When enabled, Record speaks each direction fully, gives you an 8-second pose break, then counts down before recording. Stop ends the sequence.",12,MUTED));
        Switch a=new Switch(this);a.setText("Stop at planned shot length");a.setTextColor(FG);a.setChecked(autoStop);a.setOnCheckedChangeListener((b,on)->autoStop=on);c.addView(a);
        c.addView(text("Cues use your current phone audio output. Pair AirPods in Android settings. Cues stay quiet during recording.",12,MUTED));

        c.addView(button("Hear the direction",false,()->{if(!countdown&&(capture==null||!capture.isRecording()))speech.speak(shot.instruction);}));
        c.addView(button("Switch front / back",false,()->{if(countdown||capture!=null&&capture.isRecording()){toast("Stop this take first.");return;}if(capture!=null&&live){live=false;capture.switchCamera();}else{desiredLens=desiredLens==CameraSelector.LENS_FACING_FRONT?CameraSelector.LENS_FACING_BACK:CameraSelector.LENS_FACING_FRONT;save();status.setText((desiredLens==CameraSelector.LENS_FACING_BACK?"Back":"Front")+" camera selected · tap Start camera");}}));c.addView(button("Next shot →",false,()->{if(countdown||capture!=null&&capture.isRecording()){toast("Stop this take first.");return;}shotIndex=(shotIndex+1)%shots.size();boolean reopen=live;session=false;save();render();if(reopen){cameraPlaceholder.setVisibility(View.GONE);startCamera();}}));c.addView(button("End shoot & review",false,()->{stopTake();session=false;if(capture!=null)capture.stopPreview();if(capture==null||!capture.isRecording())switchTab(2);else{reviewAfterSave=true;status.setText("Saving your last take…");}}));content.addView(c);
        content.addView(text("Pose model observes only while this shoot is open. Camera and microphone stop when you leave the app. Drone clips can be imported; aircraft control is not connected.",12,MUTED));
    }
    private void startShoot(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},41);return;}cameraPlaceholder.setVisibility(View.GONE);startCamera();}
    private void startCamera(){if(live)return;if(capture!=null&&capture.isRecording()){toast("The previous take is still saving. Try again in a moment.");return;}if(capture!=null){capture.close();capture=null;}if(pose!=null){pose.close();pose=null;}session=true;speech.stopListening();pose=new PoseCoach((cue,count,latency)->runOnUiThread(()->{if(!session||tab!=1)return;if(capture!=null&&!capture.isRecording()&&!countdown){status.setText("On-device pose · "+count+" visible points · "+latency+" ms");framingView.setText(cue);if(voice&&SystemClock.elapsedRealtime()-lastCue>12000){lastCue=SystemClock.elapsedRealtime();speech.speak(cue);}}}));pose.setMode(style);pose.setEnabled(isPoseShot());capture=new CaptureController(this,preview,new CaptureController.Listener(){public void onReady(){live=true;desiredLens=capture.getLensFacing();save();if(captureAction!=null)captureAction.setText("Record · 3 sec");status.setText("Shoot active · "+speech.describeAudioRoute());if(!capture.isAnalysisAvailable())framingView.setText("Live pose analysis unavailable on this camera. Follow your shot cue and check the preview.");else if(!isPoseShot())framingView.setText("Person-framing advice is off for this object shot. Follow your scene cue.");if(sequenceActive)prepareSequenceShot();}public void onRecordingStarted(){countdown=false;speech.stop();recordStart=SystemClock.elapsedRealtime();timerView.setText("● Recording — cues quiet");handler.post(tick);}public void onRecordingFinished(Uri uri,long duration){handler.removeCallbacks(tick);if(pose!=null)pose.setEnabled(session&&isPoseShot());if(duration>300){Shot s=recordingShot!=null?recordingShot:shots.get(shotIndex);takes.add(new Take(uri,s.id,s.title,s.caption,duration));save();}timerView.setText("Take saved · "+String.format(Locale.US,"%.1f",duration/1000.0)+" sec");status.setText("Review your take in Assemble");if(reviewAfterSave){reviewAfterSave=false;switchTab(2);}else if(sequenceActive){if(shotIndex+1<shots.size()){shotIndex++;save();render();cameraPlaceholder.setVisibility(View.GONE);startCamera();}else{sequenceActive=false;session=false;switchTab(2);status.setText("Your shot sequence is ready to review.");}}}public void onError(String e){sequenceActive=false;countdown=false;handler.removeCallbacks(tick);live=false;if(captureAction!=null)captureAction.setText("Start camera");toast(e);status.setText(e);if(pose!=null)pose.setEnabled(session&&isPoseShot());if(reviewAfterSave){reviewAfterSave=false;switchTab(2);}}});capture.setLensFacing(desiredLens);capture.setAnalyzer(pose);capture.startPreview();}
    private final Runnable tick=new Runnable(){public void run(){if(capture==null||!capture.isRecording())return;long elapsed=SystemClock.elapsedRealtime()-recordStart;String recordingStatus=String.format(Locale.US,"● %.1fs / %ds · quiet on set",elapsed/1000.0,recordingShot.targetDurationMs/1000);timerView.setText(recordingStatus);status.setText(recordingStatus);if((autoStop||sequenceActive)&&elapsed>=recordingShot.targetDurationMs){capture.stopRecording();return;}handler.postDelayed(this,100);}};
    private boolean isPoseShot(){if(style.toLowerCase(Locale.ROOT).contains("product"))return false;String title=shots.get(shotIndex).title.toLowerCase(Locale.ROOT);return !title.contains("cutaway")&&!title.contains("world")&&!title.contains("detail")&&!title.contains("fabric")&&!title.contains("product")&&!title.contains("texture")&&!title.contains("sleeve");}
    private void startCountdown(){if(busy){toast("Wait for local processing to finish.");return;}if(!live||capture==null){toast("Start the shoot camera first.");return;}if(countdown||capture.isRecording())return;if(guideSequence&&!sequenceActive){sequenceActive=true;prepareSequenceShot();return;}speech.stop();speech.stopListening();pose.setEnabled(false);countdown=true;int generation=++countdownGeneration;recordingShot=shots.get(shotIndex);cueView.setText(recordingShot.instruction);count(3,generation);}
    private void prepareSequenceShot(){
        speech.stopListening();pose.setEnabled(false);countdown=true;
        int generation=++countdownGeneration;recordingShot=shots.get(shotIndex);
        cueView.setText(recordingShot.instruction);
        framingView.setText("Follow this direction. Your pose break starts after the cue.");
        status.setText("Direction first · Stop ends the sequence");timerView.setText("Hear your next scene");
        if(voice)speech.speakThen(recordingShot.instruction,()->beginPoseBreak(generation),()->spokenCueFailed(generation));
        else beginPoseBreak(generation);
    }
    private boolean countdownCurrent(int generation){return generation==countdownGeneration&&countdown&&session;}
    private void beginPoseBreak(int generation){
        if(!countdownCurrent(generation)||!sequenceActive)return;
        status.setText("Pose break · 8 seconds · Stop ends the sequence");timerView.setText("Get ready for your next take");
        handler.postDelayed(()->{if(countdownCurrent(generation)&&sequenceActive)count(3,generation);},8000);
    }
    private void spokenCueFailed(int generation){
        if(!countdownCurrent(generation))return;
        stopTake();
        timerView.setText("Paused before recording");
        status.setText("Offline voice unavailable. Turn spoken direction off to use the visual countdown.");
    }
    private void count(int n,int generation){
        if(!countdownCurrent(generation))return;
        if(n==0){speech.stop();capture.startRecording();return;}
        timerView.setText("Starting in "+n+"…");status.setText("Starting in "+n+"… tap Stop to cancel");
        long earliest=SystemClock.elapsedRealtime()+1000;
        if(voice)speech.speakThen(Integer.toString(n),()->{
            if(countdownCurrent(generation))handler.postDelayed(()->count(n-1,generation),Math.max(350,earliest-SystemClock.elapsedRealtime()));
        },()->spokenCueFailed(generation));
        else handler.postDelayed(()->count(n-1,generation),1000);
    }
    private void cancelCountdown(){countdown=false;++countdownGeneration;}
    private void stopTake(){sequenceActive=false;cancelCountdown();handler.removeCallbacks(tick);if(capture!=null)capture.stopRecording();speech.stopListening();speech.stop();if(pose!=null)pose.setEnabled(session&&isPoseShot());}
    private void editPage(){
        headline("Put your story together.","Choose takes, tighten the cuts, add your words.");LinearLayout c=card();c.addView(text("LOOK & FEEL",11,LIME));EditText title=input(reelTitle,"Optional reel title");title.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){reelTitle=s.toString();}public void afterTextChanged(android.text.Editable e){}});c.addView(title);c.addView(spinner(new String[]{"Clean","Warm","Cinematic","Auto balance"},look,s->{look=s;save();}));c.addView(text("Local presets or automatic neutral/exposure balance · vertical 720p · up to 12 cuts / 3 minutes. Originals stay intact. English speech can be transcribed offline.",12,MUTED));c.addView(button("Import clips from my phone",false,()->pickClips()));c.addView(button("Try synthetic demo clips",false,()->loadDemo()));content.addView(c);
        long total=0;for(int i=0;i<takes.size();i++){Take t=takes.get(i);final int index=i;if(t.selected)total+=t.outMs-t.inMs;LinearLayout row=card();CheckBox selected=new CheckBox(this);selected.setText(t.title);selected.setTextColor(FG);selected.setTextSize(19);selected.setChecked(t.selected);selected.setOnCheckedChangeListener((b,on)->{t.selected=on;save();updateSelectionSummary();});row.addView(selected);row.addView(text(String.format(Locale.US,"%.1f → %.1fs  ·  %s",t.inMs/1000.0,t.outMs/1000.0,t.caption.isEmpty()?"No caption":t.caption),13,MUTED));row.addView(button("Trim & typography",false,()->editTake(index)));row.addView(button("Generate offline subtitles",false,()->transcribeTake(index)));if(!t.subtitles.isEmpty()){row.addView(text(t.subtitles.size()+" timed subtitle drafts · review before export",12,LIME));row.addView(button("Review subtitle words & timing",false,()->reviewSubtitles(index)));}row.addView(button("Preview take",false,()->previewVideo(t.uri)));if(i>0)row.addView(button("Move earlier",false,()->{Collections.swap(takes,index,index-1);save();render();}));content.addView(row);}
        selectionSummary=text("",13,LIME);updateSelectionSummary();content.addView(selectionSummary);content.addView(button("Export my reel",true,()->export()));content.addView(button(pendingPack==null?"Save clips + edits for my laptop":"Save ready edit package",false,()->{if(pendingPack==null)packageProject();else requestPackDocument();}));if(pendingPack!=null)content.addView(button("Create a fresh edit package",false,()->packageProject()));content.addView(text("Portable ZIP includes the selected original clips and editable cut list. Choose a local folder; up to 512 MB of originals. Transfer through Office Kit separately.",12,MUTED));if(lastVideo!=null){content.addView(button("Play exported reel",false,()->previewVideo(lastVideo)));content.addView(button("Share reel",false,()->share(lastVideo,"video/mp4")));}if(lastEdit!=null){content.addView(button("Save editable cut list to Files",false,()->saveEditDocument()));content.addView(button("Share editable cut list",false,()->share(lastEdit,"application/json")));}
    }
    private void updateSelectionSummary(){if(selectionSummary==null)return;long total=0;int selected=0;for(Take take:takes)if(take.selected){total+=take.outMs-take.inMs;selected++;}selectionSummary.setText(selected+" selected / "+takes.size()+" takes · "+String.format(Locale.US,"%.1fs",total/1000.0)+" · up to 12 cuts / 3 min");}
    private void transcribeTake(int index){if(busy)return;if(!transcriber.isModelAvailable()){toast("Offline English speech model is not installed. Use manual text.");return;}Take take=takes.get(index);setBusy(true);status.setText("Listening to this clip locally… no microphone is opened");transcriber.transcribe(take.uri,new ClipTranscriber.Listener(){public void onComplete(List<SubtitleCue> cues,long ms){setBusy(false);take.subtitles=cues;take.captionOrigin="whisper-tiny.en-draft";save();render();status.setText(cues.isEmpty()?"No speech found. Add manual text if needed.":"Offline subtitle draft ready · "+String.format(Locale.US,"%.1fs",ms/1000.0)+" · review the words");if(!cues.isEmpty())reviewSubtitles(index);}public void onError(String e){setBusy(false);status.setText(e);toast(e);}});}
    private void reviewSubtitles(int index){Take take=takes.get(index);LinearLayout form=column();form.setPadding(dp(18),dp(8),dp(18),dp(8));ArrayList<EditText> words=new ArrayList<>(),starts=new ArrayList<>(),ends=new ArrayList<>();for(SubtitleCue cue:take.subtitles){form.addView(text("Source timestamps in seconds · short cues fit up to 4 lines",11,MUTED));EditText a=input(SubtitleTime.format(cue.startMs),"Start seconds"),b=input(SubtitleTime.format(cue.endMs),"End seconds"),w=input(cue.text,"Subtitle words");a.setInputType(8194);b.setInputType(8194);form.addView(a);form.addView(b);form.addView(w);starts.add(a);ends.add(b);words.add(w);}ScrollView scroll=new ScrollView(this);scroll.addView(form);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Review your subtitle draft").setView(scroll).setPositiveButton("Save reviewed subtitles",null).setNeutralButton("Remove subtitles",(d,w)->{take.subtitles.clear();take.captionOrigin="manual";save();render();}).setNegativeButton("Later",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{ArrayList<SubtitleCue> cues=new ArrayList<>();for(int i=0;i<words.size();i++){String w=words.get(i).getText().toString().trim();long start=SubtitleTime.parse(starts.get(i).getText().toString()),end=SubtitleTime.parse(ends.get(i).getText().toString());if(start<0||end<=start||end>take.durationMs)throw new IllegalArgumentException();if(!w.isEmpty())cues.add(new SubtitleCue(start,end,w));}take.subtitles=cues;take.captionOrigin="creator-reviewed-offline-asr";save();dialog.dismiss();render();}catch(Exception e){toast("Use valid subtitle times inside the source clip.");}}));dialog.show();}
    private void pickReference(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,52);}
    private void analyzeReference(Uri uri){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}setBusy(true);status.setText("Inspecting selected frames locally…");references.analyze(uri,new ReferenceAnalyzer.Listener(){public void onResult(String summary,long elapsedMs){setBusy(false);referenceSummary=summary;save();tab=0;render();status.setText("Reference observations ready. Describe the trend's story, then build a plan.");}public void onError(String error){setBusy(false);status.setText(error);toast(error);}});}
    private void packageProject(){
        if(busy)return;
        discardPendingPack();setBusy(true);status.setText("Packing your selected originals and edits locally…");
        int generation=++saveGeneration;
        packager.export(takes,reelTitle,look,new ProjectPackager.Listener(){
            public void onProgress(long bytes){if(generation==saveGeneration)status.setText(String.format(Locale.US,"Packing originals locally · %.1f MB",bytes/1048576.0));}
            public void onComplete(File file,long bytes){
                if(generation!=saveGeneration){file.delete();return;}
                setBusy(false);pendingPack=file;save();
                if(getLifecycle().getCurrentState().isAtLeast(androidx.lifecycle.Lifecycle.State.RESUMED))requestPackDocument();
                else status.setText("Edit package ready. Return to Assemble to choose a save folder.");
            }
            public void onError(String message){if(generation!=saveGeneration)return;setBusy(false);status.setText(message);toast(message);}
        });
    }
    private void requestPackDocument(){
        if(pendingPack==null||!pendingPack.isFile()){discardPendingPack();toast("Create the package again before saving.");return;}
        if(!getLifecycle().getCurrentState().isAtLeast(androidx.lifecycle.Lifecycle.State.RESUMED))return;
        Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"MiniFilm-edit-package.zip");
        try{startActivityForResult(intent,54);}catch(Exception error){status.setText("Edit package is ready. Files could not open; try Save ready edit package again.");}
    }
    private void discardPendingPack(){if(pendingPack!=null){pendingPack.delete();pendingPack=null;save();}}
    private File restorePendingPack(String name){try{if(!name.matches("minifilm-pack-[0-9]+\\.zip"))return null;File file=new File(getCacheDir(),name);if(!file.getCanonicalFile().getParentFile().equals(getCacheDir().getCanonicalFile())||!file.isFile()||file.length()<=0||file.length()>ProjectPackager.MAX_ORIGINAL_BYTES+8388608L)return null;return file;}catch(Exception ignored){return null;}}
    @Override protected void onResume(){super.onResume();if(pendingPack!=null&&!busy&&tab==2){render();status.setText("Your previously prepared edit package is ready to save.");}}

    private void copyProjectPack(Uri destination){
        File source=pendingPack;pendingPack=null;save();if(source==null){toast("Create the package again before saving.");return;}
        int generation=++saveGeneration;savingDocument=true;setBusy(true);status.setText("Saving your portable edit package…");
        new Thread(()->{String error=null;try(InputStream in=new FileInputStream(source);OutputStream out=getContentResolver().openOutputStream(destination,"w")){
            if(out==null)throw new IOException();byte[] buffer=new byte[65536];int read;while((read=in.read(buffer))!=-1){if(generation!=saveGeneration)throw new IOException("Cancelled");out.write(buffer,0,read);}out.flush();
        }catch(Exception problem){error="Package save did not finish. The chosen document may be partial; save again with a new name. Original clips are safe.";}finally{source.delete();}
        String result=error;handler.post(()->{if(generation!=saveGeneration)return;savingDocument=false;setBusy(false);status.setText(result==null?"Clips + edits saved to your chosen folder. Office Kit transfer is ready to test.":result);if(result!=null)toast(result);});},"Save-edit-package").start();
    }
    private void saveEditDocument(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"MiniFilm-project.json");startActivityForResult(i,53);}
    private void copyEditDocument(Uri destination){Uri source=lastEdit;if(source==null)return;int generation=++saveGeneration;setBusy(true);savingDocument=true;status.setText("Saving your editable cut list…");new Thread(()->{String error=null;try(InputStream in=getContentResolver().openInputStream(source);OutputStream out=getContentResolver().openOutputStream(destination,"w")){if(in==null||out==null)throw new IOException();byte[] buffer=new byte[8192];int read;long count=0;while((read=in.read(buffer))!=-1){if(generation!=saveGeneration)throw new IOException("Cancelled");count+=read;if(count>1048576)throw new IOException();out.write(buffer,0,read);}out.flush();}catch(Exception e){error="Could not save the cut list. Choose a writable local folder and try again.";}final String result=error;handler.post(()->{if(generation!=saveGeneration)return;savingDocument=false;setBusy(false);status.setText(result==null?"Editable cut list saved to your chosen folder":result);if(result!=null)toast(result);});},"Save-cut-list").start();}
    private void pickClips(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("video/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,51);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==54){if(result==RESULT_OK&&data!=null&&data.getData()!=null)copyProjectPack(data.getData());else discardPendingPack();return;}if(request==53&&result==RESULT_OK&&data!=null&&data.getData()!=null){copyEditDocument(data.getData());return;}if(request==52&&result==RESULT_OK&&data!=null&&data.getData()!=null){analyzeReference(data.getData());return;}if(request!=51||result!=RESULT_OK||data==null)return;ArrayList<Uri> uris=new ArrayList<>();if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)uris.add(data.getData());for(Uri u:uris){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}MediaMetadataRetriever m=new MediaMetadataRetriever();try{m.setDataSource(this,u);long duration=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION));if(duration<=0||m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO)==null)throw new IllegalArgumentException();takes.add(new Take(u,"import","Imported take "+(takes.size()+1),"",duration));}catch(Exception e){toast("That clip could not be read. Try a local MP4.");}finally{try{m.release();}catch(Exception ignored){}}}save();tab=2;render();}
    private void editTake(int i){Take t=takes.get(i);LinearLayout form=column();form.setPadding(dp(20),dp(10),dp(20),dp(10));EditText start=input(SubtitleTime.format(t.inMs),"In point / seconds"),end=input(SubtitleTime.format(t.outMs),"Out point / seconds"),caption=input(t.caption,"Typography (used when no subtitles)"),title=input(t.title,"Take title");start.setInputType(8194);end.setInputType(8194);form.addView(text("In / out in seconds · total "+SubtitleTime.format(t.durationMs)+"s",12,MUTED));form.addView(start);form.addView(end);form.addView(title);form.addView(caption);form.addView(text("Keep typography to 4 short lines. Longer text must be shortened before export. Take headings fit one line; omit the reel title for caption-only output.",12,MUTED));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Make this cut yours").setView(form).setPositiveButton("Save",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{long in=SubtitleTime.parse(start.getText().toString()),out=SubtitleTime.parse(end.getText().toString());if(in<0||out<=in||out>t.durationMs||out-in<250)throw new IllegalArgumentException();t.inMs=in;t.outMs=out;t.title=title.getText().toString();t.caption=caption.getText().toString();save();dialog.dismiss();render();}catch(Exception e){toast("Use a valid cut at least 0.25 sec long within this take.");}}));dialog.show();}
    private void export(){if(busy)return;if(takes.stream().noneMatch(t->t.selected)){toast("Select at least one take.");return;}setBusy(true);if("Auto balance".equals(look)){status.setText("Inspecting local color samples… keep the app open");autoColor.analyze(takes,new AutoColorBalance.Listener(){public void onComplete(List<AutoColorBalance.Balance> balances,long elapsed){startReelExport(balances);}public void onError(String error){setBusy(false);status.setText(error);toast(error);}});}else startReelExport(Collections.emptyList());}
    private void startReelExport(List<AutoColorBalance.Balance> balances){status.setText("Exporting on your phone… keep the app open");exporter.export(takes,reelTitle,look,balances,new ReelExporter.Listener(){public void onProgress(int p){status.setText("Exporting locally · "+p+"%");}public void onComplete(Uri v,Uri e){setBusy(false);lastVideo=v;lastEdit=e;save();render();status.setText("Your reel is ready · saved to Movies / MiniFilm");}public void onError(String e){setBusy(false);status.setText(e);toast(e);}});}
    private void loadDemo(){if(busy)return;int generation=++demoGeneration;setBusy(true);status.setText("Creating synthetic demo clips locally…");DemoAssets.create(this,new DemoAssets.Listener(){public void onReady(List<Take> t){if(generation!=demoGeneration)return;setBusy(false);takes.addAll(t);tab=2;save();render();status.setText("Synthetic demo · no camera or microphone was used");}public void onError(String e){if(generation!=demoGeneration)return;setBusy(false);toast(e);status.setText(e);}});}
    private void previewVideo(Uri u){Uri safe=u;if("file".equals(u.getScheme()))safe=FileProvider.getUriForFile(this,"dev.minifilm.director.files",new File(u.getPath()));Intent i=new Intent(this,PreviewActivity.class).setData(safe).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(i);}catch(Exception e){toast("This video could not be opened.");}}
    private void share(Uri u,String type){Intent i=new Intent(Intent.ACTION_SEND).setType(type).putExtra(Intent.EXTRA_STREAM,u).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share your film"));}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] grants){super.onRequestPermissionsResult(r,p,grants);if(r==41){toast("Permissions updated. Tap Start camera when you're ready.");}else if(r==42)toast("Tap Speak my brief when you're ready.");}
    @Override protected void onStop(){super.onStop();sequenceActive=false;session=false;cancelCountdown();handler.removeCallbacks(tick);if(capture!=null)capture.stopPreview();speech.stop();speech.stopListening();if(pose!=null)pose.setEnabled(false);live=false;if(captureAction!=null)captureAction.setText("Start camera");save();}
    @Override protected void onDestroy(){++saveGeneration;++demoGeneration;if(capture!=null)capture.close();if(pose!=null)pose.close();speech.close();planner.close();transcriber.close();references.close();exporter.cancel();packager.close();autoColor.close();super.onDestroy();}
    private void save(){try{JSONObject o=new JSONObject();if(pendingPack!=null)o.put("pendingPack",pendingPack.getName());o.put("lens",desiredLens).put("guideSequence",guideSequence).put("reelTitle",reelTitle).put("referenceSummary",referenceSummary).put("brief",brief).put("style",style).put("look",look).put("source",planSource).put("shot",shotIndex).put("voice",voice);JSONArray ss=new JSONArray();for(Shot s:shots)ss.put(new JSONObject().put("id",s.id).put("title",s.title).put("cue",s.instruction).put("caption",s.caption).put("duration",s.targetDurationMs));o.put("shots",ss);JSONArray tt=new JSONArray();for(Take t:takes){JSONArray subs=new JSONArray();for(SubtitleCue cue:t.subtitles)subs.put(new JSONObject().put("start",cue.startMs).put("end",cue.endMs).put("text",cue.text));tt.put(new JSONObject().put("subtitles",subs).put("captionOrigin",t.captionOrigin).put("uri",t.uri.toString()).put("id",t.shotId).put("title",t.title).put("caption",t.caption).put("duration",t.durationMs).put("in",t.inMs).put("out",t.outMs).put("selected",t.selected));}o.put("takes",tt);if(lastVideo!=null)o.put("lastVideo",lastVideo.toString());if(lastEdit!=null)o.put("lastEdit",lastEdit.toString());getSharedPreferences("shoot",0).edit().putString("state",o.toString()).apply();}catch(Exception ignored){}}
    private void recoverTakes(){File dir=new File(getFilesDir(),"takes");File[] files=dir.listFiles((d,n)->n.endsWith(".mp4"));if(files==null)return;for(File f:files){Uri u=Uri.fromFile(f);if(takes.stream().anyMatch(t->t.uri.equals(u)))continue;MediaMetadataRetriever m=new MediaMetadataRetriever();try{m.setDataSource(f.getAbsolutePath());long duration=Long.parseLong(m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION));if(duration>300)takes.add(new Take(u,"recovered","Recovered take","",duration));}catch(Exception ignored){}finally{try{m.release();}catch(Exception ignored){}}}}
    private void restore(){try{JSONObject o=new JSONObject(getSharedPreferences("shoot",0).getString("state","{}"));pendingPack=restorePendingPack(o.optString("pendingPack",""));desiredLens=o.optInt("lens",CameraSelector.LENS_FACING_FRONT);if(desiredLens!=CameraSelector.LENS_FACING_BACK)desiredLens=CameraSelector.LENS_FACING_FRONT;guideSequence=o.optBoolean("guideSequence",false);reelTitle=o.optString("reelTitle","");referenceSummary=o.optString("referenceSummary","");brief=o.optString("brief",brief);style=o.optString("style",style);look=o.optString("look",look);planSource=o.optString("source",planSource);shotIndex=o.optInt("shot",0);voice=o.optBoolean("voice",true);JSONArray ss=o.optJSONArray("shots");if(ss!=null)for(int i=0;i<ss.length();i++){JSONObject s=ss.getJSONObject(i);shots.add(new Shot(s.getString("id"),s.getString("title"),s.getString("cue"),s.getString("caption"),s.getLong("duration")));}JSONArray tt=o.optJSONArray("takes");if(tt!=null)for(int i=0;i<tt.length();i++){JSONObject t=tt.getJSONObject(i);Take a=new Take(Uri.parse(t.getString("uri")),t.getString("id"),t.getString("title"),t.getString("caption"),t.getLong("duration"));a.inMs=t.getLong("in");a.outMs=t.getLong("out");a.selected=t.getBoolean("selected");a.captionOrigin=t.optString("captionOrigin","manual");JSONArray cues=t.optJSONArray("subtitles");if(cues!=null)for(int j=0;j<cues.length();j++){JSONObject cue=cues.getJSONObject(j);a.subtitles.add(new SubtitleCue(cue.getLong("start"),cue.getLong("end"),cue.getString("text")));}takes.add(a);}if(o.has("lastVideo"))lastVideo=Uri.parse(o.getString("lastVideo"));if(o.has("lastEdit"))lastEdit=Uri.parse(o.getString("lastEdit"));}catch(Exception ignored){}}
}
