// Captures only the public synthetic wireframe in an isolated browser context.
const { chromium } = require('/Users/sanju/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('path');
(async () => {
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:440,height:1000},deviceScaleFactor:2,reducedMotion:'reduce'});
  const page = await context.newPage();
  const errors=[];page.on('pageerror', e=>errors.push(e.message));
  await page.clock.install();
  await page.goto('http://127.0.0.1:4173/index.html#camera');
  const snap=async name=>{await page.locator('.phone').screenshot({path:path.join(__dirname,'assets',name+'.png')});};
  await snap('camera');
  await page.locator('.objective-pill').click();
  await page.locator('[name="brief"]').fill('A 20-second jacket reveal. Show the texture, the walk, and a confident final pose.');
  await page.locator('#brief-form').evaluate(el=>el.requestSubmit());
  await snap('objective');
  await page.evaluate(()=>location.hash='reference');
  await page.locator('[data-action="load-reference-sample"]').click();
  for(let i=0;i<5;i++) await page.locator('[data-reference-review]').nth(i).check();
  await page.locator('.scroll-content').evaluate(el=>el.scrollTop=el.scrollHeight);
  await snap('reference');
  await page.locator('[data-action="apply-reference"]').click();
  await snap('confirmation');
  await page.locator('[data-action="confirm-apply-reference"]').click();
  await snap('plan');
  await page.locator('[data-action="start-director"]').click();
  await snap('pose');
  await page.clock.runFor(1700);await snap('countdown3');
  await page.clock.runFor(1000);await snap('countdown2');
  await page.clock.runFor(1000);await snap('countdown1');
  await page.clock.runFor(1100);await snap('recording');
  await page.clock.runFor(3000);await snap('cut');
  await page.clock.runFor(50000);
  await page.waitForFunction(()=>location.hash==='#reel');await snap('editor');
  await page.locator('[data-action="review-clip"]').click();await snap('review');
  await page.locator('[data-action="keep"]').click();
  await page.locator('.finishing-tools summary').click();
  await page.locator('[data-view="subtitles"]').click();await snap('captions');
  await page.evaluate(()=>location.hash='reel');
  await page.locator('[data-action="project"]').click();
  await page.locator('#project-name').fill('Jacket reveal — guided demo');await snap('save');
  await page.locator('[data-action="save-project"]').click();
  await page.locator('#app-nav [data-view="projects"]').click();await snap('projects');
  const downloadPromise=page.waitForEvent('download');
  await page.locator('[data-action="download-saved-project"]').click();
  const dl=await downloadPromise; await dl.saveAs(path.resolve('output/demo/synthetic-project.json'));
  await context.close();await browser.close();
  console.log(JSON.stringify({errors,shots:16,download:'synthetic-project.json',provenance:'Actual scripted public wireframe; no sensors, reference fetch or model inference.'}));
})().catch(e=>{console.error(e);process.exit(1)});
